### ISSUE TITLE
As a customer I want a detailed cost estimation with a maximum of 750 euro

### ISSUE THREAD

**Issue by koenschauwaert** [ccmteamap/robot#8]
- [ ] test

**Comment by RuvendeGroote** [comment]
**SUB TASKS**
- [x] Break down project into parts that have a discrete functionality.
- [x] Find ways to implement those functionalities.
- [x] Write down the material needed to create those implementations.
- [x] Look up current market prices of those materials.
- [x] Combine all the estimations and see if it exceeds the maximum budget.
- [x] If it exceeds the budget, find ways to cut down the costs or research different implementations.
